### PR TITLE
esn-frontend-calendar#499: Moved build dependencies to the appropriate place

### LINKED ISSUE #499: [TASK][Notification component] Integrate the event notification component into Calendar
#### Prerequisites

Must be done after:

- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/529
- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/537

#### Subtasks

- [ ] Choose a place in the UI to put the event notification icon button in the Calendar app.
- [ ] Configure the dav client's Authorization headers correctly.
- [ ] Adapt the component's style to the Calendar app (the component must not have a shadow DOM for this to be possible).

### PR DESCRIPTION
**Pull request by itswillta**
Partially resolves https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/499.

### CODE REVIEW

**Comment by itswillta** [comment]
@rezk2ll Btw can't we ignore `package-lock.json` already?

**Review by rezk2ll — APPROVED** [review]

**Comment by rezk2ll** [comment]
> @rezk2ll Btw can't we ignore `package-lock.json` already?

I'll ignore it right after you merge this

**Comment by itswillta** [comment]
@rezk2ll You can ignore it now.

**Comment by rezk2ll** [comment]
done

**Pull request merged**
